### PR TITLE
Improve performance of `New-`/`Set-JiraIssue` on instances with large quantities of fields

### LINKED ISSUE #515: Poor performance of `New-JiraIssue`/`Set-JiraIssue` when Jira instance has lots of custom fields
## Description

`New-JiraIssue` and `Set-JiraIssue` perform very poorly when a Jira instance has a large quantity of custom fields. Our development instance has 630 CFs defined and calling `Set-JiraIssue` (with about takes roughly 8 seconds to complete. The underlying HTTP PUT to Jira's REST API is only about 150ms of this.

## Steps To Reproduce

1. Configure Jira with a lot (~500) custom fields.
2. Either:
  * Create an issue with `New-JiraIssue`
  * Update an existing issue with `Set-JiraIssue`
  In either case, use the `-Fields` parameter to set a few custom fields for the given issue type.
3. Observe performance.

## Expected behavior

Response time is relatively performant/semi-aligned with Jira web UI

## Your Environment

JiraPS 2.14.7

## Possible Solution

New-JiraIssue and Set-JiraIssue appear to be calling `Get-JiraField` in a loop for each KVP in `-Fields`. While the call to `Get-JiraField` contains a `-Name` parameter, the underlying API is unfiltered. This means that, when creating an issue and specifying 3 fields in the `-Fields` parameter against an instance with 500 custom fields, we end up retrieving (and parsing!) 1,500 custom field entries.

Two options seem to be available here:
* Hoist the call to `Get-JiraField` out of the `foreach` loops [here](https://github.com/AtlassianPS/JiraPS/blob/2c04d5689430cfbf9c9c9739e1d6ca975cb97653/JiraPS/Public/New-JiraIssue.ps1#L134-L140) and [here](https://github.com/AtlassianPS/JiraPS/blob/2c04d5689430cfbf9c9c9739e1d6ca975cb97653/JiraPS/Public/Set-JiraIssue.ps1#L159-L173)
* Use field info from CreateMeta/EditMeta which, AFAICT, has:
 * All of the fields available for a given issue type (or issue in its current state)
 * Their field IDs
 * Those fields's structural/schematic requirements (required or not, type, etc.)
 We're already fetching CreateMeta in `New-JiraIssue` [here](https://github.com/AtlassianPS/JiraPS/blob/2c04d5689430cfbf9c9c9739e1d6ca975cb97653/JiraPS/Public/New-JiraIssue.ps1#L66), so this is likely a straightforward fix.

### PR DESCRIPTION
**Pull request by hmmwhatsthisdo**
### Description

This PR adjusts the functionality of `New-JiraIssue` and `Set-JiraIssue` to only call `Get-JiraField` once (if `-Fields` is set) instead of once per entry in the `-Fields` hashtable.

Additionally, both cmdlets will resolve numerical IDs for custom fields if users specify fields in that way (i.e. `-Fields @{12345 = $foo}` is equivalent to `-Fields @{customfield_12345 = $foo}`)

### Motivation and Context

`Get-JiraField` takes a `-Name` parameter, however the underlying API call is not filtered by name. This means that every field in the instance (visible to the current user) is retrieved for each key in `-Fields`. This means network traffic/CPU usage/time spent scales quadratically in practice (linear to the number of CFs in the API call and the number of CFs in the instance).

By moving `Get-JiraField` out of this loop (thus only calling it once), we can cache field data instead of hammering Jira's API for it.

Closes #515.

#### Improvement Areas
We currently query the whole instance's fields which, on larger (or poorly-organized) instances, may:
* Be very large
* Include duplicate fields used in different contexts than the user's

Using the CreateMeta and EditMeta endpoints (with `Get-JiraIssueCreateMetadata` and `Get-JiraIssueEditMetadata`) would reduce response size and limit fields to ones that are actually relevant to the current project/issue context.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] My code follows the code style of this project.
- [ ] I have added Pester Tests that describe what my changes should do.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by lipkau — APPROVED** [review]

**Review by lipkau — CHANGES_REQUESTED** [review]
Fix tests

**Comment by hmmwhatsthisdo** [comment]
> Fix tests

Will do, I'll give it a look this evening. Thanks for approving the CI pass!

**Comment by hmmwhatsthisdo** [comment]
@lipkau Dug into this a bit - the problem appears to be that the unit tests use a mock for `Get-JiraField` that only supports the field-specific implementation. `New-JiraIssue` appears to be easy to fix, but `Set-JiraIssue` might need more nuance to it.

(As an aside, it would be in our best interest to upgrade to Pester 5)

**Comment by hmmwhatsthisdo** [comment]
@lipkau Tests should be green again. Can you re-approve the workflows?

**Review by lipkau — APPROVED** [review]

**Comment by lipkau** [comment]
shall we document something about further refactoring in this area?

**Comment by hmmwhatsthisdo** [comment]
> shall we document something about further refactoring in this area?

When I'm back at my desk, I can cut an issue for:
* Applying similar treatment to `Invoke-JiraIssueTransition`
* Updating `New-`/`Set-JiraIssue` to use metadata endpoints
* Update to Pester 5

Anything else you see as being necessary here?

**Comment by hmmwhatsthisdo** [comment]
@lipkau Issues have been filed. Can you merge the PR when you have a moment?

**Pull request merged**
