### PR TITLE
Createmeta update

### PR DESCRIPTION
**Pull request by robertmbaker**
### Description

The createmeta API call has changed. As per: https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html

The path for the API call and the data returned have changed format. This causes the New-JiraIssue commandlet to fail. This change addresses both the change in URI and the change in format.
### Motivation and Context

This change addresses an API issue with the createmeta API call.

https://github.com/AtlassianPS/JiraPS/issues/473

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] My code follows the code style of this project.
- [x] I have added Pester Tests that describe what my changes should do.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by seanportercci** [comment]
+1

**Review by mkellerman-relativity — APPROVED** [review]

**Comment by teunito** [comment]
+1

**Comment by mkellerman** [comment]
@lipkau Any way we can push a new version manually while we are working on refactoring the CI workflows?

**Comment by pccasto** [comment]
I did a hand-edit, taking the patch, and applying the pieces to the combined JiraPS.psm1 file.  THANK you very much for the patch!!  Things are working nicely against an Enterprise Jira Server 9.4.3 installation.

**Review by lipkau — APPROVED** [review]
added to the alpha release

**Pull request merged**
