### PR TITLE
Add-JiraFixVersion - Resolves Issue #40 

### PR DESCRIPTION
**Pull request by Dejulia489**
cloeses #40

### CODE REVIEW

**Comment by Dejulia489** [comment]
Removed * from Functions to export so it would not get lost in the merge to master. 

This can be reverted to * in Dev if needed

**Comment by lipkau** [comment]
I feel like releasing `New-JiraFixVersion` should be released bundled with:
* **`Get-JiraFixVersion`**
* `Merge-JiraFixVersion`
* `Move-JiraFixVerion`
* **`Set-JiraFixVersion`**
* **`Remove-JiraFixVersion`**

_PS: the **bold** ones I see as the most important_

**Comment by lipkau** [comment]
closes #38

**Comment by Dejulia489** [comment]
@lipkau Agreed, can you please assign issue #40 to me for this PR.

**Comment by lipkau** [comment]
continues by #151

**Pull request closed without merging**
