### PR TITLE
Config server handling

### PR DESCRIPTION
**Pull request by axxelG**

### CODE REVIEW

**Comment by lipkau** [comment]
Hi @axxelG 

sorry that this PR has been ignored for so long.
Can you please update the Test Cases and the file locations?

_by pushing to the branch in your fork, the PR will be extended automatically_

also: can you describe the relation between this issue and #71? does it make sense to merge them?

**Comment by replicaJunction** [comment]
Suggest we close both this PR and #71 in favor of the upcoming changes I've discussed in #45.

**Comment by lipkau** [comment]
Agreed

**Comment by axxelG** [comment]
This PR was meant to move the config handling to a separate private function so that it could be merged without breaking anything and the late changes for the config file handling will be easier to implement. But I'm fine that it is closed now.

**Pull request closed without merging**
